### ISSUE TITLE
Can't assume tsconfig.json is at the same location with package.json

### ISSUE THREAD

**Issue by hyrious** [gadget-inc/esbuild-dev#3]
I'm making an electron app, the project structure is like:

```
/package.json
	/src
		/main
			index.ts
			tsconfig.json 	// for node.js env
		/render
			tsconfig.json 	// for browser env
```

https://github.com/gadget-inc/esbuild-dev/blob/a77d709db01507aa9961c29a4b99e941c4571d26/src/Compiler.ts#L31-L35

When I run `esbuild-dev ./path/to/main/index.ts`, it says:

```
Error: couldnt find tsconfig.json near ./path/to/main/index.ts
```

Also, provide an option to disable type checking entirely (because vscode does it for us)?

**Comment by airhorns** [comment]
Is that the way you've decided to structure your project, or how all electron projects are set up? Supporting that would require quite a bit of extra smarts in the way we find tsconfigs which I'd like to avoid if possible, but patches are always welcome. 

> Also, provide an option to disable type checking entirely (because vscode does it for us)?

`esbuild-dev` doesn't do any typechecking at all right now, but we are using the tsconfig right now to power some of the options we pass into esbuild itself, as well as enumerate all the files we need to build ahead of time.

**Comment by hyrious** [comment]
> Is that the way you've decided to structure your project, or how all electron projects are set up?

It's not necessary to set up electron projects like that, for example we can _lift up_ main's tsconfig to root path, and everything will work fine.

Since esbuild-dev is designed to _execute_ node.js scripts, the render's tsconfig should never be used.

I think we can avoid looking for tsconfigs by ourself, see comments below.

> Also, provide an option to disable type checking entirely?

Here I made a mistake of assuming you're looking for tsconfig to do type checking since ts-node-dev would do that. However, [esbuild did find tsconfig by itself](https://esbuild.github.io/api/#tsconfig):

> Normally the build API automatically discovers `tsconfig.json` files and reads their contents during a build. ...This can be useful if you need to do multiple builds of the same code **with different settings**.

The point is you're using tsconfig's `include` or maybe `files` to cache as much files' build results as you could. However some tsconfigs may not have these fields because some users are not intend to use tsc to compile their codes, they may just use babel or esbuild (like me) and leave type cheking to editors or IDEs.

As a result, build one file at a time is more acceptable (and is not too slow, is it?):

https://github.com/gadget-inc/esbuild-dev/blob/a77d709db01507aa9961c29a4b99e941c4571d26/src/Compiler.ts#L77-L78

All `esbuild-dev` need to do is let the build result runnable on current node engine (by tweaking `target` field) and watch dependents' changes.

**Comment by airhorns** [comment]
> As a result, build one file at a time is more acceptable (and is not too slow, is it?):

Sadly, it is significantly slower in my benchmarking to build one file at a time because the invocation overhead for esbuild dominates the time spent building (which is crazy). It's a lot faster to give it whole groups of files up front, and, it enables esbuild's incremental mode where it can rebuild only files that change without having to keep a huge amount of build handles in memory.

I think we could probably keep this style of upfront file discovery while still respecting multiple tsconfigs though, as `esbuild-dev` is just using TypeScript itself to discover those files, and it definitely knows how to support tsconfig inheritance just fine. Would you like to submit a PR that adds support for this?

**Comment by hyrious** [comment]
I'm glad to contribute to your repo. I've noticed you have changed the behavior in 137e9fbab6a9f313194a6e6a811c747e586cf708.
It looks like there's nothing I can do for you? Maybe you should add notices in readme that tells users to write correct tsconfig.json :)

If you would like to support files not in tsconfig, then you need some way to find file dependencies by yourself. For example, [`@hyrious/esbuild-dev` did this](https://github.com/hyrious/esbuild-dev/blob/b8cad9c3774cd6eb057df41ce8396acafbacfd0a/src/utils.ts#L100).

**Comment by airhorns** [comment]
Yeah, I agree that discovery without using TypeScript would be better. My ideal solution would be if `esbuild` could do the discovery itself -- it already knows how to do fast module resolution when you use `bundle: true`. Right now though, it doesn't support traversing the module graph with `bundle: false` it seems, and I think not bundling folks' node code would be ideal in order to match their expectations of how things might get run, and to facilitate debugging of not enormous files. I can't find the original issue but the esbuild author indicated he wasn't super interested in adding that feature, so I went with the TypeScript option but I don't think it is that long for this world.
